services:
  chrome-node-1:
    container_name: chrome-node-1
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: selenium/node-chrome:4.10.0
    networks:
    - selenium_network
  chrome-node-2:
    container_name: chrome-node-2
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: selenium/node-chrome:4.10.0
    networks:
    - selenium_network
  firefox-node-1:
    container_name: firefox-node-1
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: selenium/node-firefox:4.10.0
    networks:
    - selenium_network
  firefox-node-2:
    container_name: firefox-node-2
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: selenium/node-firefox:4.10.0
    networks:
    - selenium_network
  firefox-node-3:
    container_name: firefox-node-3
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    image: selenium/node-firefox:4.10.0
    networks:
    - selenium_network
  php:
    container_name: php-container
    image: php:7.4-apache
    networks:
    - default
    ports:
    - 80:80
    volumes:
    - ./php:/var/www/html
version: '3.3'
